# Generated by Django 5.2.4 on 2025-07-18 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(blank=True, help_text='ID del todo en el API externo', null=True, unique=True)),
                ('title', models.CharField(help_text='Título del pendiente', max_length=500)),
                ('completed', models.BooleanField(default=False, help_text='¿Está completado el todo?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Usuario propietario del todo', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Todo/Pendiente',
                'verbose_name_plural': 'Todos/Pendientes',
                'ordering': ['external_id', 'id'],
            },
        ),
    ]
